=head1 Global Files List

This document contains a list of all the files found in the Global subdirectory of the SEEDtk data directory.

=over 4

=item uni_roles.tbl

A list of the universal roles required for metagenomic analysis. Each role in this file occurs at most once in
most genomes and occurs in almost all prokaryotic genomes known. The file is tab-delimited, and each line contains
(0) a function ID, (1) a count, and (2) a function description.

=item rep_roles.tbl

A list of the roles used to isolate representative genomes. The file contains one role ID per line.

=item representative.genomes

A list of genomes considered to be representative. That is, all other bacterial genomes are fairly close and all
genomes in this set are fairly distant. The file is tab-delimited. Each record contains (0) a genome ID and (1) the
genome name.

=back